"""add mobile to users

Revision ID: a39ed4bc5357
Revises: 0b4c86779edd
Create Date: 2026-07-30 09:58:52.971867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39ed4bc5357'
down_revision: Union[str, Sequence[str], None] = '0b4c86779edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.String(length=15), nullable=False))
    op.create_unique_constraint(None, 'users', ['mobile'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###
